spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/FitnessStudio
    username: postgres
    password: DPht*3Vl$QW9Y40$5H3BLoxuQ
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.mail.ru
    port: 465
    username: gontchar.test@mail.ru
    password: C7fkTS3X54ntJ33VzH7c
    default-encoding: UTF-8
    test-connection: true
    protocol: smtps
jwt:
  secret: LdgOJyWTB4ZXPXUJ6SJlmmNVBvTPHN31FGAHyYAe52bsPuQma2
  issuer: FitnessStudio

